[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lqfs_lib = { path = "../lqfs_lib" }
raft = "0.7.0"
slog = "2.7.0"
slog-term = "2.9.0"
uuid = "1.4.0"

